version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  clickhouse_data:
